# POST http://localhost:5000/api/v1/users/login
# content-type: application/json

# {
#   "email": "email2@email2.com",
#   "password": "123456"
# }

# POST http://localhost:5000/api/v1/users/register
# content-type: application/json

# {
#   "email": "email2@email2.com",
#   "password": "123456"
# }

# GET http://localhost:5000/api/v1/users/logout
# content-type: application/json

# GET http://localhost:5000/api/v1/data/getSources
# content-type: application/json

# GET http://localhost:5000/api/v1/data/getQuotes
# content-type: application/json

# POST http://localhost:5000/api/v1/data/addSource
# content-type: application/json

PATCH http://localhost:5000/api/v1/data/update-quote
content-type: application/json

{
  "body": "a new update to the quote",
  "_id": "5f954f75357c430cfe33270f"
}

# POST http://localhost:5000/api/v1/data/addQuote
# content-type: application/json

# {
#   "body": "This is a brand new quote we just added another.",
#   "tags": ["quotes", "notes"]
# }
