# POST http://localhost:5000/api/v1/users/login
# content-type: application/json

# {
#   "email": "email2@email2.com",
#   "password": "123456"
# }

# POST http://localhost:5000/api/v1/users/register
# content-type: application/json

# {
#   "email": "email2@email2.com",
#   "password": "123456"
# }

# GET http://localhost:5000/api/v1/users/logout
# content-type: application/json

# GET http://localhost:5000/api/v1/data/getSources
# content-type: application/json

# GET http://localhost:5000/api/v1/data/getQuotes
# content-type: application/json

# POST http://localhost:5000/api/v1/data/addSource
# content-type: application/json

# {
#   "sourceTitle": "My extra extra Cool Source",
#   "author": "Me"
# }

PATCH http://localhost:5000/api/v1/data/5f9a686713a4d004faed6797
content-type: application/json

{
  
}

# POST http://localhost:5000/api/v1/data/addQuote
# content-type: application/json

# {
#   "body": "This is a brand new quote we just added another.",
#   "tags": ["quotes", "notes"]
# }
